services:
  db:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fastapi_app
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  backend:
    build:
      context: .
    container_name: backend
    restart: always
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:password@db:5432/fastapi_app
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge